name: "Test action-install-earthly"
on:
  pull_request:
  push:
    branches:
      - "main"
      - "releases/*"
      - "acb/*"

jobs:
  unit:
    name: earthly +all
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: ${{ !env.ACT && 'npm' || '' }}
          node-version: "16.x"
      - uses: ./
      - run: which earthly
      - run: env
      - run: earthly +all
  # Below are tests specific to the github actions, which ensure the actions-setup code works with GHA
  latest:
    name: Test Latest Version Install
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: ${{ !env.ACT && 'npm' || '' }}
          node-version: "16.x"
      - run: npm install
      - run: npm run package
      - uses: ./
      - run: earthly --version
      - run: earthly --version | grep 'earthly\(\.exe\)\? version v'
  specific:
    name: Test Specific Version Install
    strategy:
      matrix:
        # windows was not available < v0.5.15
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: ${{ !env.ACT && 'npm' || '' }}
          node-version: "16.x"
      - run: npm install
      - run: npm run package
      - uses: ./
        with:
          version: 0.5.15
      - run: earthly --version
      - run: earthly --version | grep 'earthly\(\.exe\)\? version v0\.5\.15'
  patch-range:
    name: Test Patch Range Version Install
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: ${{ !env.ACT && 'npm' || '' }}
          node-version: "16.x"
      - run: npm install
      - run: npm run package
      - uses: ./
        with:
          version: 0.6.*
      - run: earthly --version
      - run: earthly --version | grep 'earthly\(\.exe\)\? version v0\.6\.'
  major-range:
    name: Test Patch Range Version Install
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: ${{ !env.ACT && 'npm' || '' }}
          node-version: "16.x"
      - run: npm install
      - run: npm run package
      - uses: ./
        with:
          version: ^0.6.1
      - run: earthly --version | grep 'earthly\(\.exe\)\? version v0\.6\.'
